name: Fyooz Studio
favicon: null
layout_spectrum: 0.22291
typography_spectrum: 0.19670483306981623
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#404041'
    - '#d7df21'
    - '#000000'
    - '#9ba02e'
    - '#00ff00'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
