name: Fyooz Studio
favicon: null
layout_spectrum: 0.49263
typography_spectrum: 0.19670483306981623
title: 'welcome!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#404041'
    - '#d7df21'
    - '#000000'
    - '#9ba02e'
    - '#00ff00'
  brandStrength: 0.6875
  lightness: 0.5
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
